format = """
[░▒▓](#31748f)\
$os\
[](bg:#d7827e fg:#31748f)\
$directory\
[](fg:#d7827e bg:#394260)\
$git_branch\
$git_status\
$nix_shell\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[](fg:#1d2230)\
$hostname\
$custom\
\n$character"""

[directory]
style = "fg:#e5eeff bg:#d7827e"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Files" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Images" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#d7827e bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#d7827e bg:#394260)]($style)'

[nix_shell]
symbol = "󱄅"
style = "bg:#212736"
format = '[[ $symbol $state ](fg:#9ccfd8 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#d7827e bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#d7827e bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#d7827e bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#d7827e bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[   $time ](fg:#b8c0e0 bg:#1d2230)]($style)'

[hostname]
disabled = false
ssh_only = false
detect_env_vars = ['OS_CONTAINER']
format = '[$ssh_symbol](fg:#89dceb) on [$hostname](fg:#d7827e)'

[custom.venv]
description = "Shows virtual environment's directory"
command = '''basename "$VIRTUAL_ENV"'''
when = '''[[ -n "$VIRTUAL_ENV" ]]'''
format = ' \([$output](fg:#d7827e)\)'

[os]
disabled = false
style = "bg:#31748f fg:#9ccfd8"

[os.symbols]
Arch = "  " 
Ubuntu = "  "
Debian = "  "
Alpine = "  "
Kali = "  "
